In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from time import time
from tqdm import tqdm
import matplotlib.pyplot as plt
from pyarrow import csv


In [13]:
# data read. use pyarrow

train = csv.read_csv('../input/ventilator-pressure-prediction/train.csv').to_pandas()
test = csv.read_csv('../input/ventilator-pressure-prediction/test.csv').to_pandas()

### Columns
1. id : index
2. breath_id : breath index. 같은 row들은 한번의 호흡임
3. R : 기도가 얼마나 막혀있는지 나타내는 변수. R이 높을수록 vent가 어려움? 추가조사필요. unique : 5, 20, 50
4. C : 폐가 얼마나 순응적인지 나타내는 변수. C가 높을수록 vent가 쉬움? unizue : 10, 20, 50
5. time_step : timestep
6. u_in : 흡기 솔레노이드 밸브 제어 입력. 0~100까지의 수치를 가짐. 높을수록 많이 주입하는듯
7. u_out : 호기 솔레노이드 밸브 제어 입력. 0 or 1의 수치를 가짐
8. pressure(y) : 기도에서 측정된 압력

In [16]:
train.info()  # no missing data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6036000 entries, 0 to 6035999
Data columns (total 8 columns):
 #   Column     Dtype  
---  ------     -----  
 0   id         int64  
 1   breath_id  int64  
 2   R          int64  
 3   C          int64  
 4   time_step  float64
 5   u_in       float64
 6   u_out      int64  
 7   pressure   float64
dtypes: float64(3), int64(5)
memory usage: 368.4 MB


In [23]:
print(train["breath_id"].unique())
print(len(train["breath_id"].unique()))
# 전체 호흡은 125749까지 있지만 총 호흡 수는 75450. 중간중간 공백이 있음

[     1      2      3 ... 125743 125745 125749]
75450


In [22]:
print(train["C"].unique())
print(train["R"].unique())

[50 20 10]
[20 50  5]
